# Generated by Django 4.1.4 on 2022-12-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janatawifi_sqldata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jatatawifi_stock_market',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jatatawifi_stock_market',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jatatawifi_stock_market',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='jatatawifi_stock_market',
            name='open',
            field=models.FloatField(),
        ),
    ]
