# Generated by Django 4.1.4 on 2022-12-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janatawifi_sqldata', '0002_alter_jatatawifi_stock_market_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jatatawifi_stock_market',
            name='close',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jatatawifi_stock_market',
            name='high',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jatatawifi_stock_market',
            name='low',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jatatawifi_stock_market',
            name='open',
            field=models.CharField(max_length=100),
        ),
    ]
